# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ— ](bold red) "
vicmd_symbol = "[â®](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[conda]
symbol = "ğŸ…’ "
format = "[$symbol$environment](dimmed green) "

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) at "
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "blue bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[git_status]
style = "bold yellow"
format = '([\[$all_status$ahead_behind\] ]($style)) '
conflicted = '[=$count](bold red)'
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = '[?$count](red)'
stashed = '[\$$count](yellow)'
modified = '[!$count](green)'
staged = '[+$count](green)'
renamed = '[Â»$count](green)'
deleted = '[âœ˜$count](red)'

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%r"
use_12hr = true
style = "bold yellow"

